// Generated by LiveScript 1.2.0
(function(){
  var myrobot, tr;
  importScripts('../base-robot.js');
  myrobot = (function(superclass){
    var prototype = extend$((import$(myrobot, superclass).displayName = 'myrobot', myrobot), superclass).prototype, constructor = myrobot;
    prototype.onIdle = function(){
      this.turn_turret_right(90);
    };
    prototype.onWallCollide = function(){
      this.move_opposide(10);
      this.turn_left(90);
      this.move_forwards(100);
    };
    prototype.onHit = function(){
      this.yell("Oops!");
      this.move_backwards(100);
      this.shoot();
    };
    prototype.onEnemySpot = function(){
      this.yell("Fire!");
      this.shoot();
      this.shoot();
      this.turn_turret_right(20);
      this.shoot();
      this.shoot();
      this.turn_turret_left(20);
      this.shoot();
      this.shoot();
    };
    function myrobot(){
      myrobot.superclass.apply(this, arguments);
    }
    return myrobot;
  }(BaseRobot));
  tr = new myrobot("Boss 1");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
