// Generated by LiveScript 1.2.0
(function(){
  var YaRobot, tr;
  importScripts('../base-robot.js');
  YaRobot = (function(superclass){
    var idleCount, dir, prototype = extend$((import$(YaRobot, superclass).displayName = 'YaRobot', YaRobot), superclass).prototype, constructor = YaRobot;
    idleCount = 0;
    dir = 0;
    prototype.doSearch = function(){
      this.turn_turret_right(10);
      this.turn_right(10);
	  this.shoot();
    };
    prototype.onIdle = function(){
      var myAngle, forward, tinyShoot, leftDist, rightDist;
      this.idleCount++;
      myAngle = this.me.angle % 360;
      if (this.myVarEnemy) {
        tinyShoot = Math.random() * 10;
        leftDist = myAngle + 360 - this.myVarEnemy[0].angle;
        if (leftDist > 360) {
          leftDist = leftDist - 360;
        }
        rightDist = this.myVarEnemy[0].angle - myAngle;
        if (rightDist < 0) {
          rightDist = 360 + rightDist;
        }
        if (leftDist !== rightDist) {
          if (Math.random() > 0.5) {
            forward = true;
          }
          if (leftDist > rightDist) {
            this.turn_turret_right(rightDist + 5 + tinyShoot);
          } else {
            this.turn_turret_left(leftDist + 5 + tinyShoot);
          }
          this.shoot();
        } else {
          this.shoot();
        }
        this.myVarEnemy = undefined;
      } else {
        if (this.idleCount > 3) {
          this.doSearch();
          if (this.idleCount > 4) {
            this.doSearch();
            if (this.idleCount > 5) {
              this.doSearch();
            }
          }
          return;
        }
        if(this.dir%2==0){
          this.turn_turret_left(30);
          this.turn_left(30);
          this.move_forwards(15);
          this.shoot();
        }else{
          this.turn_turret_left(30);
          this.turn_left(30);
          this.move_forwards(15);
          this.shoot();
        }
      }
    };
    prototype.onWallCollide = function(){
      this.move_opposide(10);
      this.turn_left(90);
      this.idleCount = 0;
    };
    prototype.onHit = function(){
      this.idleCount = 0;
      this.yell("No! I'm hit!");
    };
    prototype.onEnemySpot = function(){
      this.dir++;
      this.myVarEnemy = this.enemySpot;
      this.shoot();
      this.yell("Enemy spotted!");
      this.idleCount = 0;
    };
    function YaRobot(){
      YaRobot.superclass.apply(this, arguments);
    }
    return YaRobot;
  }(BaseRobot));
  tr = new YaRobot("The final boss");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);